services:
    Softspring\DoctrineChangeLogBundle\EventListener\CollectChangesListener:
        arguments: ['@Softspring\DoctrineChangeLogBundle\Collector\ChangesStack']
        tags: ['kernel.event_subscriber']

    Softspring\DoctrineChangeLogBundle\EventListener\CollectRequestListener:
        arguments: ['@request_stack']
        tags: ['kernel.event_subscriber']

    Softspring\DoctrineChangeLogBundle\EventListener\CollectUserListener:
        arguments: ['@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface']
        tags: ['kernel.event_subscriber']
