services:
    Softspring\DoctrineChangeLogBundle\Annotation\AnnotationReader: ~

    Softspring\DoctrineChangeLogBundle\EventListener\DoctrineChangesListener:
        arguments:
            $eventDispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
            $metadataReader: '@Softspring\DoctrineChangeLogBundle\Annotation\AnnotationReader'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Softspring\DoctrineChangeLogBundle\Collector\ChangesStack: ~