services:
    sfs_doctrine_changelog.storage.big_query_client:
        class: Google\Cloud\BigQuery\BigQueryClient

    Softspring\DoctrineChangeLogBundle\Storage\BigQuery\Schema:
        arguments:
            $bigQueryClient: '@sfs_doctrine_changelog.storage.big_query_client'
            $config: '%sfs_doctrine_changelog.storage.big_query%'
            $logger: '@logger'

    Softspring\DoctrineChangeLogBundle\Storage\BigQuery\ChangesProcessor:
        arguments:
            $schema: '@Softspring\DoctrineChangeLogBundle\Storage\BigQuery\Schema'
            $logger: '@logger'

    Softspring\DoctrineChangeLogBundle\Storage\BigQuery\BigQueryManager:
        arguments:
            $schema: '@Softspring\DoctrineChangeLogBundle\Storage\BigQuery\Schema'
            $changesProcessor: '@Softspring\DoctrineChangeLogBundle\Storage\BigQuery\ChangesProcessor'

    Softspring\DoctrineChangeLogBundle\Storage\BigQueryStorageDriver:
        arguments:
            $manager: '@Softspring\DoctrineChangeLogBundle\Storage\BigQuery\BigQueryManager'

    Softspring\DoctrineChangeLogBundle\Storage\StorageDriverInterface:
        alias: 'Softspring\DoctrineChangeLogBundle\Storage\BigQueryStorageDriver'